openapi: 3.0.0
info:
  title: Shop API
  description: Lambda based REST API
  version: '1'
components:
  schemas:
    GetProductsListResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            format: uuid
          title:
            type: string
          description:
            type: string
          price:
            type: number
          count:
            type: integer
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        fieldsError:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
    productId:
      type: string
      format: uuid
    GetProductByIdResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        price:
          type: number
        count:
          type: integer
paths:
  /products:
    get:
      summary: Get Products
      description: Returns a full list of available products
      operationId: product-service-dev-getProductsList
      parameters: []
      tags: []
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductsListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create Product
      description: Creates product and returns it
      operationId: product-service-dev-createProduct
      parameters: []
      tags: []
      responses:
        '201':
          description: Product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductByIdResponse'
        '400':
          description: Body validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /products/{productId}:
    get:
      summary: Get Single Product
      description: Returns a single product by it's id
      operationId: product-service-dev-getProductById
      parameters:
        - name: productId
          in: path
          description: Unique product identifier
          required: true
          schema:
            $ref: '#/components/schemas/productId'
      tags: []
      responses:
        '200':
          description: Product object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductByIdResponse'
        '400':
          description: Wrong Id type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
servers:
  - url: https://t181oeitnb.execute-api.us-east-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: dev
