service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
    REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:DeleteObject
            - s3:GetObject
          Resource: arn:aws:s3:::uploaded-files-aws-bucket/uploaded/*
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource: arn:aws:s3:::uploaded-files-aws-bucket/parsed/*

plugins:
  - serverless-better-credentials
  - serverless-webpack
  - serverless-offline

custom:
  bucketName: uploaded-files-aws-bucket
  webpack:
    webpackConfig: webpack.config.js

package:
  individually: true

resources:
  Resources:
    UploadedFilesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
              AllowedHeaders:
                - "*"
              AllowedOrigins:
                - "*"

functions:
  importFileParser:
    handler: src/handlers/importFileParser.importFileParser
    events:
      - s3:
          bucket: !Ref UploadedFilesBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
  importProductsFile:
    handler: src/handlers/importProductsFile.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
